---
- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
      - ../vars

- name: Check if OS is supported
  fail: msg="OS {{ ansible_os_family }} is unsupported"
  when: not iscsi_target.supported_os

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Start iscsi service
  service: name={{ item }} state=started enabled=true
  with_items: iscsi_target.services
